# Generated by Django 2.2.24 on 2021-11-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(verbose_name='Дата задачи'),
        ),
    ]
