# Generated by Django 2.2.24 on 2021-11-06 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20211106_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateTimeField(verbose_name='Дата задачи'),
        ),
    ]
